# Default values for PHP.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
envDeploy: dev
replicaCount: 1
image:
  repository: harbor.hazloagil.com/hazloagil/mysql-backup
  tag: 0.3.6
  pullPolicy: IfNotPresent
# define environment variables here as a map of key: value

secrets:
  WORDPRESS_DATABASE_USER: cus_alimentosyuno_user
  WORDPRESS_DATABASE_PASSWORD: DHH73bcb2yt2vubdvjiby3t6evF
  WORDPRESS_USERNAME: alimentosyuno
  WORDPRESS_PASSWORD: FJ38h37g37bcbfbfb
configs:
  WORDPRESS_SKIP_INSTALL: "yes"
  WORDPRESS_RESET_DATA_PERMISSIONS: "yes"
  WORDPRESS_DATABASE_NAME: cus_alimentosyuno_db
  WORDPRESS_LAST_NAME: wordpress
  WORDPRESS_EMAIL: jespinoza@hazloagil.com
  WORDPRESS_FIRST_NAME: base
  TINI_SUBREAPER: true
  WORDPRESS_SCHEME: https
  WORDPRESS_TABLE_PREFIX: wp_
  WORDPRESS_BLOG_NAME: "Tu Base Wordpress"
  WP_CACHE: true
env:
# enable this flag to use knative serve to deploy the app
knativeDeploy: false

# HorizontalPodAutoscaler
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  cpuTargetAverageUtilization: 80
  memoryTargetAverageUtilization: 80

# Canary deployments
# If enabled, Istio v1.5+ and Flagger need to be installed in the cluster
canary:
  enabled: false
  progressDeadlineSeconds: 60
  canaryAnalysis:
    interval: "1m"
    threshold: 5
    maxWeight: 60
    stepWeight: 20
    # WARNING: Canary deployments will fail and rollback if there is no traffic that will generate the below specified metrics.
    metrics:
      requestSuccessRate:
        threshold: 99
        interval: "1m"
      requestDuration:
        threshold: 1000
        interval: "1m"
  # The host is using Istio Gateway and is currently not auto-generated
  # Please overwrite the `canary.host` in `values.yaml` in each environment repository (e.g., staging, production)
  host: acme.com

service:
  name: cus-alimentosyuno-cl
  type: ClusterIP
  externalPort: 8443
  internalPort: 8443
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: traefik\ntraefik.ingress.kubernetes.io/router.entrypoints: web, websecure\ntraefik.ingress.kubernetes.io/router.tls: true\ntraefik.ingress.kubernetes.io/router.tls.certresolver: ledns"
#resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
probePath: /
scheme: HTTPS
livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
  initialDelaySeconds: 60


# custom ingress annotations on this service
ingress:
  host: alimentosyuno.cl
  annotations:
#      kubernetes.io/ingress.class: nginx

# values we use from the `jx-requirements.yml` file if we are using helmfile and helm 3
jxRequirements:
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false

    # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
    apiVersion: "extensions/v1beta1"

    # shared ingress annotations on all services
    annotations:
    #  kubernetes.io/ingress.class: nginx
