apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secret
data:
  WORDPRESS_DATABASE_USER: {{ .Values.secrets.WORDPRESS_DATABASE_USER | b64enc }}
  WORDPRESS_DATABASE_PASSWORD: {{ .Values.secrets.WORDPRESS_DATABASE_PASSWORD | b64enc }}
  WORDPRESS_USERNAME: {{ .Values.secrets.WORDPRESS_USERNAME | b64enc }}
  WORDPRESS_PASSWORD: {{ .Values.secrets.WORDPRESS_PASSWORD | b64enc }}