apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ template "fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi